// scripts/build-panel.mjs
// 由 panel/ 下的可编辑源文件生成 src/panel.mjs（被 _worker.js 引用）。
// 源文件：panel/agora.css + panel/agora-views.css（拼成 PANEL_CSS）、
//        panel/app.prod.js（PANEL_JS）、panel/{admin,setup,friend}.tmpl（模板）。
// 运行：node scripts/build-panel.mjs

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const r = (p) => readFileSync(join(root, p), "utf-8");

const PANEL_CSS = r("panel/agora.css") + "\n" + r("panel/agora-views.css");
const PANEL_JS = r("panel/app.prod.js");
const ADMIN_TMPL = r("panel/admin.tmpl");
const SETUP_TMPL = r("panel/setup.tmpl");
const FRIEND_TMPL = r("panel/friend.tmpl");

const j = (s) => JSON.stringify(s);

const out = `// src/panel.mjs — GENERATED by scripts/build-panel.mjs from panel/*. Do not edit by hand.
// 编辑界面请改 panel/ 下的源文件后重新运行：node scripts/build-panel.mjs
// Editorial / Swiss 设计系统：暖纸张 · 墨黑 · 单一朱红强调色。

export const PANEL_CSS = ${j(PANEL_CSS)};

export const PANEL_JS = ${j(PANEL_JS)};

const ADMIN_TMPL = ${j(ADMIN_TMPL)};
const SETUP_TMPL = ${j(SETUP_TMPL)};
const FRIEND_TMPL = ${j(FRIEND_TMPL)};

function escHtml(s) {
  return String(s == null ? "" : s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
}

// 管理面板（base = "/<token>"，CSS/JS 从 base/app.css、base/app.js 加载）
export function adminPanelHTML(base, host) {
  return ADMIN_TMPL.split("__BASE__").join(base).split("__HOST__").join(host);
}

// 首次初始化页（TOFU）
export function setupPageHTML(host) {
  return SETUP_TMPL.split("__HOST__").join(host);
}

// 好友导入页（浏览器访问 /<uuid> 时返回）
export function friendPageHTML(uuid, host, subName, name) {
  const subUrl = "https://" + host + "/" + uuid;
  const sub = subName || "Agora";
  const greet = name && name.trim() ? name.trim() : "朋友";
  return FRIEND_TMPL
    .split("__SUBURL__").join(escHtml(subUrl))
    .split("__SUBENC__").join(encodeURIComponent(subUrl))
    .split("__SINGENC__").join(encodeURIComponent(subUrl + "?target=singbox"))
    .split("__SUBB64__").join(btoa(subUrl))
    .split("__SUBNAME__").join(escHtml(sub))
    .split("__NAME__").join(escHtml(greet));
}
`;

writeFileSync(join(root, "src/panel.mjs"), out);
console.log("✓ 已生成 src/panel.mjs（CSS " + PANEL_CSS.length + "B，JS " + PANEL_JS.length + "B）");
